language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: codydevbox@gmail.com
  api_key:
    secure: Fx8zUVveJ1ZUr85khCvWsqmEf8gvR37e9lzR/w2kRnWrVMuXpmv01JD68v5tL44hOkggPRA22h6v2AmLl9p3jOHjYnPiCs5nfvUkZIUHs/c4ZNuRMry6BwX3G7xFCT6aTf0dKQ/4wlQLXDSah1zjwSQgNDq0UGhsY6lMXb+Pfex4p+uBU2Z04Fa9d07Hskb/wE5aRMWQ9fiZ7uzoNUN7mZfCXQdDwH5r5BfBos/U7zZ2enfqbVm65wZyNXiqgyvT2mVisQSXZ/EfC5H1ihrX1JuC5wfDjmd0S0InTYBv+lnf6JBSXqWtPy+ggapin+/ssdELiP2LWT5tuJRjBLoA3y1suL746jLJS2KNhyKYeRK2FODpovVSkpUtHNbhRagbSxbpaEI1aajEAUP1hW7MK0nlLBqvQvPDYTqvtFuGaBroEuTlewQHIghKIMxXWVE3WDyPHnUidIhq2/vTzLJ3XipGc+nbZSV+jQB2XxyUKiXTmXB64nkoCpDfcZomZSjA/iKxWJO1I0lx3Ln4xSx0P3/YCalRDHkawDEMM3I+lP68VOcM7o1RltyiKf/uLIsbdPRhFhQ8wSpEe/Xa+dTn6cgG/F9pdAP+ZQDzFo6nqR9AESzMnYSyKL9x4e5CU5RL+mkHU0eX5PY/3z6ZO3BJdnsCh6VeOkmP/nMbkiRXqso=
  on:
    branch: master
    repo: codyjdalton/ts-jule
